### ISSUE TITLE
Paths to documentation sources is hard coded and hard to change

### ISSUE THREAD

**Issue by uglow** [swanky-docs/swanky-server#28]
Hi @rodleviton, I've tried moving the swanky demo site to a subfolder and watched as nothing worked. So now I'm trying to override the swanky-server Webpack config. Currently my override looks like this:

```
// Override default Swanky config

const buildConfig = require('swanky-server').buildConfig();

const basePath = __dirname + '/../../';

// Change location of snippets and source code
buildConfig.entry.snippets = [basePath + 'config/docs/bootstrap-snippets.js'];
buildConfig.entry.docs = [basePath + 'docs/docs.js'];

buildConfig.output.path = basePath + 'website';

console.log(buildConfig);

// Retrieve webpack build configuration
module.exports = buildConfig;
``` 

So if the swanky config file had the notion of a 'srcDir', which could be looked-up by swanky-server, that would probably help. It should be possible to move the config information as well (I've changed the bootstrapSnippets.js file location above), without much effort.

So some suggestions:
- [ ] Make the swanky srcDir a variable string, rather than assuming root directory
- [ ] Use the srcDir variable at run-time, to find code
- [ ] Rename bootstrapSnippets.js to something that doesn't suggest that it is related to the BootStrap library (e.g. snippet-loader.js)
- [ ] Allow the path to swanky.config.yaml to be specified, rather than assuming current working directory (low-priority)

**Comment by rodleviton** [comment]
@uglow currently it is assumed that the swanky.config.yaml will sit inside your docs folder. This can be customised in the future. To build the site assuming it is to be served from a subdirectory there is an option to add a `subdirectory: 'docs'` in the config file. This property can be renamed to `srcDir` or `serverPath` if it makes more sense. But as I understand it the current config allows you to run from any subfolder.
