### ISSUE TITLE
Simplify loader paths

### ISSUE THREAD

**Issue by uglow** [swanky-docs/swanky-server#29]
Related to #28, the expressions coming out of the glob -> RE conversion are overly complex:
https://github.com/swanky-docs/swanky-server/blob/master/config/webpack/webpack.config.js#L189

Result:
```
/^(?:\/mypath/src\/(?!\.)(?=.)[^\/]*?\.js)$/,
/^(?:\/mypath\/src\/(?:(?!(?:\/|^)\.).)*?\/(?!\.)(?=.)[^\/]*?\.js)$/,
/^(?:\/mypath\/config\/(?!\.)(?=.)[^\/]*?\.js)$/,
/^(?:\/mypath\/config\/(?:(?!(?:\/|^)\.).)*?\/(?!\.)(?=.)[^\/]*?\.js)$/,
/^(?:\/mypath\/docs\/content\/overview\.md)$/
```

These expressions could be simplified to:
```
/pathToDocsSource\/.*\.js$/
/pathToConfig\/.*\.js$/
/pathToConfig\/.*\.md$/      // I'm not sure why overview.md is being parsed as JS at this stage
```

**Comment by rodleviton** [comment]
@uglow definitely should not be processing anything but .js. Will have a look at simplifying the glob pattern and only processing js content files.

**Comment by uglow** [comment]
I think if we can set the basePath / context (I forget what Webpack calls it) variable correctly, not simply '/', then these expressions boil down to /\.(js|md)$/
