### ISSUE TITLE
Path to swanky-theme for JS webpack loader is absolute

### ISSUE THREAD

**Issue by Nighthawk14** [swanky-docs/swanky-server#31]
When trying to compile the project with a linked swanky-theme dependency the JS files of swanky-theme are not parsed by the babel-loader of webpack.

This is because the regexps to match JS files that are passed to the babel-loader includes the absolute path of swanky-theme, when if the package is linked this path changes (symlink).

```js
var jsDirs = [
    path.join(swankyConfig.meta.theme, '/*.js'),
    path.join(swankyConfig.meta.theme, '/**/*.js'),
    path.join(basepath, 'docs/', 'src/*.js'),
    path.join(basepath, 'docs/', 'src/**/*.js'),
    path.join(basepath, 'docs/', 'config/*.js'),
    path.join(basepath, 'docs/', 'config/**/*.js')
];

var jsRE = jsDirs.map((glob) => {
    return minimatch.makeRe(glob);
});

webpackConfig.module.loaders.push({
    test: jsRE,
    loader: require.resolve('babel-loader'),
    query: {
      cacheDirectory: true,
      presets: [require.resolve('babel-preset-es2015')]
    }
});
```

The regexp in the `jsRE` array contains the absolute path of swanky-theme when it should be only `\/swanky\-theme\/(?:(?!(?:\/|^)\.).)*?\/(?!\.)(?=.)[^\/]*?\.js)$/`

**Comment by rodleviton** [comment]
@Nighthawk14 is this resolved by pull request #30?

**Comment by uglow** [comment]
Unfortunately no, it is not fixed by #30. It would be good to talk about whether paths in swanky config must be absolute and relative, so we know what to expect when referring to them later.

Maybe the tasks/loadConfig() method can parse the paths into meta-properties that can be used by Webpack (same as what it currently does, but with guarantees around whether a path is absolute or not).

**Comment by Nighthawk14** [comment]
After discussion this morning we agreed that changing `swankyConfig.meta.theme` from an absolute path to `'swanky-theme'` would solve the issue :).

**Comment by uglow** [comment]
Not sure if this should be a separate issue, but this line (and possibly others), forces EVERY theme to be in a directory ending in '-theme':

https://github.com/swanky-docs/swanky-server/blob/master/src/config/webpack/webpack.config.js#L76

**Comment by rodleviton** [comment]
@uglow I will remove the `-theme` dependency but may ask for your help in tweaking/cleaning the regex.  I will submit a PR this weekend for you to take a look if you have time.
