### ISSUE TITLE
Yeoman integration

### ISSUE THREAD

**Issue by rodleviton** [swanky-docs/swanky-server#7]
**Proposed Yeoman Flow**

1. Initialise yeoman project
 `yo swanky`

2. Enter basic project details
`Your project name:`

3. Provide option to scaffold custom theme. This will generate a clone of the swanky(modified) default theme and required layout and partial files in the user working `src` directory. Name of theme will be automatically set to `project-name-theme`. The project name can be modified after setup.
`Do you require a custom theme:`

4. Reusable pattern templates. These are the html/css building blocks of an application/site. If location is not provided any reference patterns will try and resolve to the default location `src/patterns`.
`Where will your pattern templates be (src/patterns):`

5. Prompt for common swanky processor imports. This doesnt really do much other than import the relevant swanky-processor. My expectation is that there will eventually be many processors but providing a prompt for common/obvious processors may be of some value?
`Will you be documenting any source code:`
**example options**
angular 1.x
angular 2.x (ts)
react

**Comment by rodleviton** [comment]
@uglow would you mind taking a look at this flow and give me some feed back based on your experiences with the [confit-generator](https://github.com/odecee/generator-confit)?

**Comment by uglow** [comment]
Hi @rodleviton,

A couple of thoughts come to mind:
1) good
2) Why do you need the project name? Why not use a value from the package.json? If it's wrong, make it changeable in the YAML file.
3) As above, allow it to be customised by the YAML file at her than a question. 
4) "Patterns" doesn't mean anything to a new user. Are they documentation templates? Can it be customised in YAML?
5) seems like a necessary question

I guess Confit would only need to write the YAML file ( and has answer all of those questions except for the patterns one, but I'm thinking we could add a new file path called docTemplates), then run 'swanky'? Or will the generator do a bunch of other things too?

If the latter, then Confit will need to call the generator, but should be able to provide answers to it that it already has, or tell it to use a generated YAML file with the answers in it.

**Comment by rodleviton** [comment]
The main purpose of generator is just to scaffold out some boilerplate folder/file structure. At this stage just a src, folder, config file and package.json to import core. I want to keep the boilerplate as light as possible so getting up and running requires very little 'initial' learning curve.
